<robot name="sensor" xmlns:xacro="http://www.ros.org/wiki/xacro">
 
  <xacro:macro name="gps" params="sensor_name parent_link *origin">
  <xacro:property name="height1" value="0.05" />
  <xacro:property name="width" value="0.05" />
 <!-- Used for fixing robot to Gazebo 'base_link' -->
  <joint name="gpstobase" type="fixed">
    <xacro:insert_block name="origin" />
    <parent link="${parent_link}"/>
    <child link="sensor"/>
    <!--origin xyz="0 0 ${height1 / 2}" /-->
  </joint>
 <!-- Base Link -->
  <link name="sensor">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <origin xyz="0 0 1" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>
  <material name="orange">
    <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
  </material>
 
        <gazebo reference="sensor">
	    <material>Gazebo/Orange</material>
	    <sensor name="gps_sensor" type="gps">
	    <always_on>true</always_on>
	    <topic>__default_topic__</topic>
	    <updateRate>4.0</updateRate>
            <plugin name="gazebo_ros_gps" filename="libhector_gazebo_ros_gps.so">
                <updateRate>4.0</updateRate>
                <bodyName>sensor</bodyName>
                <frameId>sensor</frameId>
                <topicName>gps/fix</topicName>
                <velocityTopicName>gps/fix_velocity</velocityTopicName>
                <referenceLatitude>-30.06022459407145675</referenceLatitude>
                <referenceLongitude>-51.173913575780311191</referenceLongitude>
                <referenceHeading>90</referenceHeading>
                <referenceAltitude>10</referenceAltitude>
                <offset>0 0 0</offset>
                <drift>0.001 0.001 0.001</drift>
                <gaussianNoise>0.05 0.05 0.05</gaussianNoise>
                <velocityDrift>0.001 0.001 0.001</velocityDrift>
                <velocityGaussianNoise>0.5 0.5 0.5</velocityGaussianNoise>
            </plugin>
	</sensor>
        </gazebo>
  </xacro:macro>
</robot>
